# Generated by Django 3.2.20 on 2023-08-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0145_auto_20230808_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtestcase',
            name='points',
            field=models.FloatField(blank=True, null=True, verbose_name='point value'),
        ),
    ]
